### ISSUE TITLE
Support for Customer Ephemeral Key?

### ISSUE THREAD

**Issue by SignSpice** [gethop-dev/payments.stripe#12]
As far as I can tell, this is necessary for a returning customer to save and reuse previous payment methods.

**Comment by SignSpice** [comment]
Potentially helpful link:

- Java Stripe lib ephemeral key test: https://github.com/stripe/stripe-java/blob/110ae567c68aa67cfe697a6309d35e3d13c5e419/src/test/java/com/stripe/functional/EphemeralKeyTest.java

**Comment by lucassousaf** [comment]
Hi @SignSpice ! Thanks for reporting this issue. We don't expect to add support for Ephemeral Keys so soon. However, you're more than welcome to do a pull request if you're up to it.

**Comment by SignSpice** [comment]
Okay @lucassousaf, I will give it a shot! I am a Clojure newbie, so we will see how far I get. Probably will be asking a few questions as I go along.

**Comment by SignSpice** [comment]
@lucassousaf 
Opened pull request.

**Comment by lucassousaf** [comment]
This is resolved, so I'm going to close the issue. Feature added on aece79783adf05f27d9faf041538552ba057b546
